# Generated by Django 2.2.7 on 2019-11-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='note',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
