# Generated by Django 2.2.7 on 2019-11-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='note',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name="Qualité de l'appel"),
        ),
    ]
