# Generated by Django 2.2.7 on 2019-11-26 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20191126_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='note',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name="Qualité de l'appel"),
        ),
    ]
